### ISSUE TITLE
Constrain numpy <= 1.22 for numba >= 0.55

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/tricolour#87]
I think tricolour also requires this:

https://github.com/ratt-ru/QuartiCal/pull/168

**Comment by sjperkins** [comment]
> I think tricolour also requires this:
> 
> [ratt-ru/QuartiCal#168](https://github.com/ratt-ru/QuartiCal/pull/168)

Thanks for the suggestion @IanHeywood. After more digging it looks like this is called by dependency resolution issues on older versions of pip: https://github.com/numba/numba/issues/8188#issuecomment-1165162555
