### ISSUE TITLE
Evil dependency hell prevents installation

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/tricolour#89]
Current PyPi release is broken:
```
$ pip install -U pip setuptools
$ pip install tricolour
...
Successfully installed asciitree-0.3.3 dask-2021.2.0 dask-ms-0.2.6 donfig-0.8.1 entrypoints-0.4 fasteners-0.18 importlib-metadata-6.8.0 llvmlite-0.40.1 numba-0.57.1 numcodecs-0.11.0 numpy-1.24.4 python-casacore-3.5.2 pyyaml-6.0.1 scipy-1.10.1 six-1.16.0 threadpoolctl-3.2.0 toolz-0.12.0 tricolour-0.1.8 zarr-2.16.1 zipp-3.16.2
```
Note numpy-1.24.4 sneaking in there despite the pin in ``setup.py``. (How and why??) Tricolour then predictably fails with:

```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
Installing ``numpy<=1.20`` by hand leads to a numba complaint:

```
ImportError: Numba needs NumPy 1.21 or greater. Got NumPy 1.19.
```

``numba==0.54.0`` is a workaround, but there's still a dependency complaint from ``zarr``.

Then, it still needs ``psutil`` (or at least whatever dask version is brought in calls for it):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oms/.venv/tricolour/lib/python3.8/site-packages/dask/diagnostics/profile.py", line 236, in run
    psutil = import_required(
  File "/home/oms/.venv/tricolour/lib/python3.8/site-packages/dask/utils.py", line 104, in import_required
    raise RuntimeError(error_msg) from e
RuntimeError: Tracking resource usage requires `psutil` to be installed
```

...and then daskland falls over with a ``bokeh`` error, seems to be this one, old dasks need old bokehs I guess: https://stackoverflow.com/questions/74280959/attributeerror-unexpected-attribute-plot-width-to-figure-similar-attributes

Finally got it to work with
```
pip install git+https://github.com/ratt-ru/tricolour numpy\<1.20 numba==0.54.0 bokeh\<3 psutil
```
...but there's still a ``zarr`` complaint at install time, so I suspect the dask-ms zarr backend will fall over if used? 

I think a lot of this trouble stems from the original sin of an increasingly ancient numpy version pin, so is it not time to fix this problem for good?

**Comment by bennahugo** [comment]
Releases were never pushed to pypi. The pinning seems to work locally (when ensuring pip setuptools and wheel are up to date.

**Comment by bennahugo** [comment]
Scratch that I see it is uploaded - the releases on github was not kept up to date. Not sure why the pinning is not working as specified. Unfortunately I don't see a quick fix to this if the breakage is inside pip / setuptools upstream. The following does the correct pinning
```
pip install git+https://github.com/ratt-ru/tricolour.git 
```

**Comment by bennahugo** [comment]
Actually things are mislabelled looking at the tarball on pypi. I will push the current master as a new release. Think this bumpversion stuff is not quite working as expected.

**Comment by bennahugo** [comment]
Closed

**Comment by o-smirnov** [comment]
Ah yeah I see the bokeh problem. The trouble with my image builds, I was basing them off a generic "python-astro" Docker image which already included bokeh, which then caused a version tangle. Basing off a simpler image solved that.

**Comment by IanHeywood** [comment]
Is tricolour forever bound to the old version of numpy? It prevents it (as far as I can understand) from being installed alongside e.g. shadems, plus other things:

```
This behaviour is the source of the following dependency conflicts.
xarray 2023.12.0 requires numpy>=1.22, but you have numpy 1.19.5 which is incompatible.
shadems 0.5.3 requires dask-ms[xarray]<0.3.0,>=0.2.16, but you have dask-ms 0.2.6 which is incompatible.
pandas 2.2.0 requires numpy<2,>=1.22.4; python_version < "3.11", but you have numpy 1.19.5 which is incompatible.
matplotlib 3.8.2 requires numpy<2,>=1.21, but you have numpy 1.19.5 which is incompatible.
distributed 2023.12.1 requires dask==2023.12.1, but you have dask 2021.2.0 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 1.19.5 which is incompatible.
```

Trying to spruce up container builds and don't want to go down the "container per package" route...

Cheers.

**Comment by bennahugo** [comment]
On the list to upgrade it to Python 3.10, and fix data-descriptor selection in the process.

For now I would suggest installing it in a virtualenv. Why not just run this via stimela?

**Comment by IanHeywood** [comment]
No worries, thanks @bennahugo, I'll just use a separate container for now.

> Why not just run this via stimela?

I didn't use stimela for oxkat, for historical cluster-related reasons IIRC. I don't have the time to rewrite it all from scratch.

**Comment by sjperkins** [comment]
> For now I would suggest installing it in a virtualenv. Why not just run this via stimela?

I would also like to motivate for separate virtualenvs, although I realise that they may not be as space efficient as installing everything in one environment.

**Comment by IanHeywood** [comment]
Same as above, I don't want to have to re-write oxkat to use virtual environments instead of singularity. Plus compared to having to set up numerous venvs, containers are a piece of cake for the other people who use it. It's no big deal, it's still a small number of containers.

Cheers.
