### ISSUE TITLE
Testing under python3.6 broken

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/tricolour#90]
Seems there is a regression on the Actions CI. Python3.6 is no longer being provided by github.

**Comment by sjperkins** [comment]
Also, dask-ms dependencies are now 2023 as a minimum. By itself, dask dropped 3.7 support a while ago (and has just dropped 3.8) support I believe.

- https://github.com/ratt-ru/dask-ms/pull/279

**Comment by sjperkins** [comment]
It's probably running a weekly cronjob in GHA to catch these sort of things. See here for e.g.

https://github.com/ratt-ru/arcae/blob/55fb06a228c03b46dc5ff8db8e320f6d3820a68c/.github/workflows/ci.yml#L10-L11

**Comment by o-smirnov** [comment]
Do we need to keep supporting 3.6? Seems like it's becoming a hoop-jumping exercise, so let's reevaluate.

**Comment by sjperkins** [comment]
IMO, the [deadsnakes PPA](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) is a an easy solution for an Ubuntu 20.04 production system.

**Comment by bennahugo** [comment]
No longer relevant. Dropping 3.6 support due to changes in numba
